name: Site Build

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -it --rm --entrypoint /bin/sh \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          docker.io/library/ruby:latest -c "chmod 777 /srv/jekyll && jekyll build --future"

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages 
          folder: _site
          
